# Generated by Django 3.2.3 on 2021-06-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('regex_search', models.CharField(max_length=400)),
                ('regex_change', models.CharField(max_length=400)),
            ],
        ),
    ]
