# Generated by Django 3.2.3 on 2021-06-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sandbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=10)),
                ('txblank', models.CharField(blank=True, max_length=10)),
                ('txnull', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
