# Generated by Django 3.2.3 on 2021-06-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandbox',
            name='choice',
            field=models.CharField(choices=[('JP', 'JAPAN'), ('US', 'AMERICA'), ('UK', 'UNITED KINGDOM')], max_length=10, null=True),
        ),
    ]
